### ISSUE TITLE
profile.get returning undefined

### ISSUE THREAD

**Issue by n1trob4ct3r** [n1trob4ct3r/learn-node#4]
@duttaditya18 some help please?

**Comment by duttaditya18** [comment]
Now what are you building?

**Comment by n1trob4ct3r** [comment]
nothing. just learning

**Comment by n1trob4ct3r** [comment]
@duttaditya18

**Comment by duttaditya18** [comment]
I made a similar thing. See this : https://github.com/duttaditya18/learn-node-js/tree/master/ip-info

**Comment by duttaditya18** [comment]
Dude JavaScript is asynchronous.
It runs the `console.log()` in `/app.js` before having the value of `respData`.

I think, doing what you wanna do in `/profile.js` would be a better option.
